// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mdlgcpjxyfwwveykqlzb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1kbGdjcGp4eWZ3d3ZleWtxbHpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4MDI5OTUsImV4cCI6MjA3MDM3ODk5NX0.e23YIOHwR90FMnO3F27k0w-zdKtONJUB0pi3wf7aLc0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});